services:
  main-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "8000:8000"
    command: "sh backend/entrypoint.sh"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    volumes:
      - .:/app/

  postgres:
      image: postgres:15-alpine
      container_name: cat-db
      ports:
      - "${POSTGRES_PORT}:5432"
      env_file:
      - ./backend/.env
      volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env

  nginx:
    image: nginx:stable-alpine
    ports: 
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    
    

      

volumes:
  postgres_data:

