# Generated by Django 5.1.1 on 2024-09-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_breeder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_breeder',
            field=models.BooleanField(default=True, verbose_name='Is breeder'),
        ),
    ]
